NEW_PROJECT__class_based_views/NEW_PROJECT__class_based_views/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls', namespace='basic_app')),
]

NEW_PROJECT__class_based_views/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'
urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path("<int:pk>/",views.SchoolDetailView.as_view(),name='detail'),
    path("create/",views.SchoolCreateView.as_view(),name='create'),
    path("update/<int:pk>/",views.SchoolUpdateView.as_view(),name='update'),
    path("delete/<int:pk>/",views.SchoolDeleteView.as_view(),name='delete'),
]

NEW_PROJECT__class_based_views/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class School(models.Model):
    name = models.CharField(max_length = 256)
    principal  = models.CharField(max_length = 256)
    location = models.CharField(max_length = 256)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={"pk": self.pk})
    


class Student(models.Model):
    name = models.CharField(max_length = 256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    

NEW_PROJECT__class_based_views/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy

# Create your views here.


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    model = models.School
    fields = ('name','principal','location')



class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ('name','principal')


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')
    



class IndexView(TemplateView):
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'basic injection data !'
        return context





# def index(request):
#     return render(request,'index.html')




# class CBView(View):
#     def get(self,request):
#         return HttpResponse('class based views are cool!')

NEW_PROJECT__class_based_views/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
<head>
	<title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>





<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <div class="collapse navbar-collapse" id="navbarNav">

    <ul class="navbar-nav">

      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>



    </ul>

  </div>

</nav>
</div>





 
	<div class="container">
		{% block body_block %}
        
    	{% endblock body_block %}
	</div>





</body> 
</html>

NEW_PROJECT__class_based_views/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}



<div class="container">
    <h1>Delete School  ' {{school.name}} '  ??!</h1>


    <form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
    <a href='{% url 'basic_app:detail' pk=school.pk %}'>Cancel</a>
    </form>


<div>



{% endblock body_block %}

NEW_PROJECT__class_based_views/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}



<div class="container">
    <h1>Detail of all schools:</h1>
    <p>Name:      {{school_detail.name}} </p>
    <p>Principal: {{school_detail.principal}} </p>
    <p>Location:  {{school_detail.location}} </p>

    <p>Students:</p>
    <ol>
    {% for student in school_detail.students.all %}
        <p><li> {{ student.name }} who is {{student.age}} years old. </li></p>
    {% endfor %}
    </ol>
    <a href='{% url 'basic_app:update' pk=school_detail.pk %}'>Update</a>
<div>



{% endblock body_block %}

NEW_PROJECT__class_based_views/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>school_form.html</h1>

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>



<form method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>




{% endblock body_block %}

NEW_PROJECT__class_based_views/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>List of all schools:</h1>

<ol>

    {% for school in schools %}

    <p><li> <a href='{{school.id}}'>{{school.name}}</a> </li></p>
    
    {% endfor %}

</ol>

{% endblock body_block %}

NEW_PROJECT__class_based_views/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>





<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <div class="collapse navbar-collapse" id="navbarNav">

    <ul class="navbar-nav">

      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>



    </ul>

  </div>

</nav>
</div>





 
	<div class="container">
		{% block body_block %}
        
    	{% endblock body_block %}
	</div>





</body> 
</html>

NEW_PROJECT__class_based_views/templates/index.html
{% extends "base.html" %}

{% block body_block %}

<h1>Home Page</h1>

{% endblock body_block %}