learn_users_django/basic_app/urls.py
from django.urls import path
from basic_app import views

#Temlpate Tagging

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),

]

learn_users_django/learn_users_django/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='user_logout'),
    path('special/', views.special, name='special'),
]

learn_users_django/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    
    def __str__(self):
        return self.user.username

learn_users_django/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username', 'email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learn_users_django/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

#from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout


# Create your views here. 

def index(request):
    return render(request,'basic_app/index.html')


def register(request):
    
    registered = False
    if request.method == 'POST':
        
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            
            user = user_form.save()
            user.set_password(user.password)
            user.save()
    
            profile = profile_form.save(commit=False)
            profile.user = user
            
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            
            
            registered = True
            
            
        else:
            print(user_form.errors, profile_form.errors)
    
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
            
    
    
    return render(request,'basic_app/register.html',{
        'user_form':user_form,
        'profile_form':profile_form,
        'registered':registered,
    })





def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('account is not active')
        
        else:
            print('someone tried to login but field!')
            print('username : {} and password: {}'.format(username,password))
            return HttpResponse('invalid login details supplied!')
        
    else:
        return render(request,'basic_app/login.html', {})




@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('you are logged in!')

learn_users_django/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li class="navbar-brand"><a href="{% url 'index' %}">Home</a></li>
				<li class="nav navbar-nav"><a href="{% url 'admin:index' %}">Admin</a></li>
				<li class="navbar-link"><a href="{% url 'basic_app:register' %}">Register</a></li>

				{% if user.is_authenticated %}
				<li class="navbar-link"><a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				<li class="navbar-link"><a href="{% url 'basic_app:user_login' %}">Login</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>


	<div class="container">
		{% block body_block %}
        
        {% endblock body_block %}
	</div>


</body>
</html>

learn_users_django/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
	{% block body_block %}

		<div class="jumbotron">
			<h1>Learning Users in Django (index.html)</h1>
		</div>

	{% endblock body_block %}

learn_users_django/templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
	{% block body_block %}

		<div class="jumbotron">
			<h1>Please Login</h1>
            <form method="post" action="{% url 'basic_app:user_login' %}">
            	    {% csrf_token %}
                    <label for="username">Username:</label>
                    <input type="text" name="username" placeholder="Enter your username">

                    <label for="password">Password:</label>
                    <input type="text" name="password">

                    <input type="submit" name="" value="Login">
            	</form>
		</div>

	{% endblock body_block %}

learn_users_django/templates/basic_app/register.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
	{% block body_block %}

		<div class="jumbotron">
            {% if registered %}
            	<h1>Thank you for registration !</h1>                
            {% else %}
            	<h1>You can register here !</h1>
            	<h1>Please fill out the form:</h1>

            	<form method="post" enctype="multipart/form-data">
            	    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" name="" value="Register">
            	</form>


            {% endif %}
		</div>

	{% endblock body_block %}