learning_template_project/basic_app/urls.py
from django.urls import path
from basic_app import views

#Temlpate Tagging

app_name = 'basic_app'
urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_template_project/learning_template_project/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_template_project/basic_app/models.py
from django.db import models

# Create your models here.

learning_template_project/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    my_dict = {'text':'hello world', 'number':100}
    return render(request,"basic_app/index.html",my_dict)


def other(request):
    return render(request,"basic_app/other.html")


def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_template_project/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<title>other</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li class="navbar-brand"><a href="{% url 'index' %}">BRAND</a></li>
				<li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
				<li class="navbar-link"><a href="{% url 'basic_app:other' %}">Other</a></li>
			</ul>
		</div>
	</nav>


	<div class="container">
		{% block body_block %}
        
        {% endblock body_block %}
	</div>


</body>
</html>

learning_template_project/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
	{% block body_block %}


		<h1>hi !  index.html</h1>
		
		<h1>{{text|upper}}</h1>
		<h1>{{number|add:"99"}}</h1>

		<h1>{{text|cut:'hello'}}</h1>


	{% endblock body_block %}

learning_template_project/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
	{% block body_block %}
    	<h1>hi !  other.html</h1>
	{% endblock body_block %}

learning_template_project/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
	{% block body_block %}
	<h1>hi !  relative_url_templates.html</h1>

		<a href="{% url 'basic_app:other' %}"> The Other Page !</a>
		<br>
		<a href="{% url 'admin:index' %}"> Admin Page </a>
		<br>
		<a href="{% url 'index' %}"> index </a>
	
	
	{% endblock body_block %}